### ISSUE TITLE
Continual location services usage

### ISSUE THREAD

**Issue by ghost** [mobfox/MobFox-iOS-SDK#32]
We've noticed significant energy usage spikes in our app and decided to investigate. It appears your framework turns on the GPS when an ad is requested or received, and fails to ever turn it off. 

We are mediating your network through DFP and the Google Mobile Ads framework on iOS 10.

I would ask that you take a look into the usage of your location services. In the meantime, we've had to use the `+locationServicesDisabled` method to restrict your framework from accessing the GPS.

**Comment by nabriski** [comment]
Hi,



Thanks for pointing this out, we'll take a look and release a fix this
week if necessary.




On Mon, Feb 6, 2017, at 04:41 AM, rickydamelio wrote:

> We've noticed significant energy usage spikes in our app and decided
> to investigate. It appears your framework turns on the GPS when an ad
> is requested or received, and fails to ever turn it off.
> We are mediating your network through DFP and the Google Mobile Ads
> framework on iOS 10.
> I would ask that you take a look into the usage of your location
> services. In the meantime, we've had to use the
> +locationServicesDisabled method to restrict your framework from
> accessing the GPS.
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
> 




Links:

  1. https://github.com/mobfox/MobFox-iOS-SDK/issues/32

**Comment by ghost** [comment]
Hi there.

Just wondering if there is any update with this?

**Comment by nabriski** [comment]
Hi,

Yes, this was fixed in our codebase and will be part of our next release in 3-4 weeks. Will update this issue when we release.

**Comment by nabriski** [comment]
Fixed in 3.1.6

**Comment by ghost** [comment]
This is still not fixed. Have you tested using the Instruments app? GPS is enabled the moment a MobFox ad is requested and is never turned off. Shocking.

**Comment by shimisheetrit** [comment]
Most of the location services run in the background only by enabling them, you need to disable the location updates background mode in the Capabilities tab of your Xcode project. anyway, it's relevant for standard location service, we use **significant location change** service to reduce battary consumption. according to Apple docs it normally delivers events in foreground and background mode (the use of this service requires “Always” authorization from the user).

I would recommend you to select 'No' (in your app definitions) in 'Background Modes' -> 'Location updates'. it's for sure will disable standard location service.

Moreover, I have tested it and Energy Impact in Xcode, showing high consumtion only after loading the ad. In background mode the energy impact is Zero, and the locationManager:didUpdateLocations: function not getting called at all.

**Comment by ghost** [comment]
I am **not** talking about background activity. I am talking about needless consumption of the GPS while the app is in the foreground. This is completely unnecessary and you appear to be the only ad framework I have encountered that is doing this.

Don't just look in Xcode's Debug Editor, why don't you open the Instruments app to profile the GPS activity and observe how it activates and then **never turns off**.

**Comment by shimisheetrit** [comment]
You could disable location services and define it by yourself.

Moreover, MoPub SDK is the only open source ad network, and there is only functionality for enabling and disabling location services. GPS is Off in 'Instruments', and it will appear in other ad networks because location services are not enabled in those cases. no alert message (iOS 8.0 or later) is displayed, and in 'Settings' app (Privacy -> Location Services -> SomeApp) 'While Using the App' or Always' are not marked. 
Please let us know on a case which location services is enabled (also in 'Settings' app) and when running in foreground GPS is in Off state. even for partial time. a case you know for sure that location services are running and GPS is in Off state.

**Comment by ghost** [comment]
We actually cannot provide location services by ourselves because we are only using MobFox as a mediated network through DFP. Is it possible that this is the issue? Maybe there is a bug in the DFP->MobFox adapter?
